# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=25, unique=True)),
                ('device_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('device_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('device_auth', models.CharField(default='!n!t', max_length=128)),
                ('device_added', models.DateTimeField(auto_now_add=True)),
                ('device_battery', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('device_status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devread_id', models.CharField(max_length=25)),
                ('devread_depth_sensor_one', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devread_depth_sensor_two', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devread_time', models.DateTimeField(null=True, verbose_name='datetime of reading.')),
                ('devread_received', models.DateTimeField(auto_now_add=True)),
                ('devread_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riverdash.Device', to_field='device_id')),
            ],
        ),
    ]
