# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdash', '0003_monthlydischarge'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterConstants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('b', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('year', models.IntegerField(default=0)),
                ('quarter', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='monthlydischarge',
            name='quarter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlydischarge',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
