# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdash', '0004_auto_20170228_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlydischarge',
            name='river_profile',
        ),
        migrations.AddField(
            model_name='quarterconstants',
            name='river_profile',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
