# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdash', '0005_auto_20170228_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterconstants',
            name='r',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quarterconstants',
            name='rtwo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
