# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdash', '0007_auto_20170302_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageDailyDischarge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discharge_date', models.DateField(verbose_name='date for averaged discharge.')),
            ],
        ),
    ]
