# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdash', '0008_averagedailydischarge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagedailydischarge',
            name='discharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='averagedailydischarge',
            name='stage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
