# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdash', '0010_auto_20170305_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereading',
            name='devread_discharge',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='devicereading',
            name='devread_stage',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=50),
        ),
    ]
