# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdash', '0012_auto_20170307_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_height', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
