# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdash', '0014_auto_20170317_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagedailydischarge',
            name='discharge',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='averagedailydischarge',
            name='stage',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='devicereading',
            name='devread_depth_sensor_one',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='devicereading',
            name='devread_depth_sensor_two',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlydischarge',
            name='discharge',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlydischarge',
            name='stage',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quarterconstants',
            name='a',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quarterconstants',
            name='b',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quarterconstants',
            name='r',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quarterconstants',
            name='river_profile',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quarterconstants',
            name='rtwo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='setconfig',
            name='sensor_height',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
