# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdash', '0015_auto_20170320_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereading',
            name='devread_discharge',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='devicereading',
            name='devread_stage',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
